<?php
/*------------------------------------------------------------------------
 # SM Custom - Version 1.0.0
 # Copyright (c) 2015 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>
<script type="text/javascript">
//<![CDATA[
data = new Date(2013,10,26,12,00,00);
var listdeal = [];
function CountDown(date,id){
	dateNow = new Date();
	amount = date.getTime() - dateNow.getTime();
	delete dateNow;
	if(amount < 0){
		document.getElementById(id).innerHTML="Now!";
	} else{
		days=0;hours=0;mins=0;secs=0;out="";
		amount = Math.floor(amount/1000);
		days=Math.floor(amount/86400);
		amount=amount%86400;
		hours=Math.floor(amount/3600);
		if(hours < 10 ) {
			hours = '0'+hours;
		}		
		amount=amount%3600;
		mins=Math.floor(amount/60);
		if(mins < 10 ) {
			mins = '0'+mins;
		}
		amount=amount%60;
		secs=Math.floor(amount);
		if(secs < 10 ) {
			secs = '0'+secs;
		}		
		if(days != 0){out += "<div class='time-item time-day'>" + "<div class='num-time'>" + days + "</div>" +" <div class='name-time'>"+((days==1)?"Day":"Days") + "</div>"+"</div> ";}
		if(hours != 0){out += "<div class='time-item time-hour'>" + "<div class='num-time'>" + hours + "</div>" +" <div class='name-time'>"+((hours==1)?"Hour":"Hours") + "</div>"+"</div> ";}
		out += "<div class='time-item time-min'>" + "<div class='num-time'>" + mins + "</div>" +" <div class='name-time'>"+((mins==1)?"Min":"Mins") + "</div>"+"</div> ";
		out += "<div class='time-item time-sec'>" + "<div class='num-time'>" + secs + "</div>" +" <div class='name-time'>"+((secs==1)?"Sec":"Secs") + "</div>"+"</div> ";
		out = out.substr(0,out.length-2);
		document.getElementById(id).innerHTML=out;
		setTimeout(function(){CountDown(date,id)}, 1000);
	}
}
//]]>
</script>

<?php 
$list = $this->_getProducts();
$helper = Mage::helper('custom/data');
$uniqued = 'sm_custom_' . time() . rand();
$limit_header = $this->_getConfig('header_item');


if (!empty($list)) {?>
	
	

	<?php if( $this->_getConfig('custom_title_text') ){ ?>
		<div class="custom_title_text"><?php echo $this->_getConfig('custom_title_text','Custom Title'); ?></div>
	<?php } ?>
	<?php if ( $this->_getConfig('pretext') != null ) { ?>
		<div class="custom-pretext">
			<?php echo $this->_getConfig('pretext'); ?>
		</div>
	<?php } ?>

	<div id="<?php echo $uniqued; ?>" class="sm-custom">
		<div class="custom-items">
			<?php $count_item = 0; $j = 0; foreach ($list as $_product) { $j++; $count_item++;?>
			<?php 
				$specialPriceFromDate = $_product->start;
				$specialPriceToDate   = $_product->end;
				$today =  time();
				
				if($count_item > $limit_header && $today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate) ){ ?>

				<div class="custom-item">
					<div class="timer-custom">
						<label><?php echo $this->__('End in'); ?></label><div id="product_time_<?php echo $j;?>"></div>	
					</div>
					<script type="text/javascript">
					//<![CDATA[
						listdeal.push('product_time_<?php echo $j."&&||&&".date("Y/m/d", strtotime($specialPriceToDate));?>') ;
					//]]>
					</script>
				</div>
			<?php }}?>
		</div>
	</div>
	
	<?php if ($this->_getConfig('posttext') != null) { ?>
		<div class="custom-posttext"><?php echo $this->_getConfig('posttext'); ?></div>
	<?php } ?>

<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($){
	if(listdeal.length > 0){
		for(i=0;i<listdeal.length;i++)
		{
			var arr = listdeal[i].split("&&||&&"); 
			var data = new Date(arr[1]);
			CountDown(data, arr[0]);
		}	
	}
});
//]]>
</script>	
<?php } else { echo $this->__('Has no content to show!'); }; ?>