<?php
/*------------------------------------------------------------------------
 # SM Custom - Version 1.0.0
 # Copyright (c) 2015 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<script type="text/javascript">
//<![CDATA[
data = new Date(2013,10,26,12,00,00);
var listdealheader = [];
function CountDown(date,id){
	dateNow = new Date();
	amount = date.getTime() - dateNow.getTime();
	delete dateNow;
	if(amount < 0){
		document.getElementById(id).innerHTML="Now!";
	} else{
		days=0;hours=0;mins=0;secs=0;out="";
		amount = Math.floor(amount/1000);
		days=Math.floor(amount/86400);
		amount=amount%86400;
		hours=Math.floor(amount/3600);
		amount=amount%3600;
		mins=Math.floor(amount/60);
		amount=amount%60;
		secs=Math.floor(amount);
		if(days != 0){out += "<div class='time-item time-day'>" + "<div class='num-time'>" + days + "</div>" +" <div class='name-time'>"+((days==1)?"Day":"Days") + "</div>"+"</div> ";}
		if(hours != 0){out += "<div class='time-item time-hour'>" + "<div class='num-time'>" + hours + "</div>" +" <div class='name-time'>"+((hours==1)?"Hour":"Hours") + "</div>"+"</div> ";}
		out += "<div class='time-item time-min'>" + "<div class='num-time'>" + mins + "</div>" +" <div class='name-time'>"+((mins==1)?"Min":"Minutes") + "</div>"+"</div> ";
		out += "<div class='time-item time-sec'>" + "<div class='num-time'>" + secs + "</div>" +" <div class='name-time'>"+((secs==1)?"Sec":"Seconds") + "</div>"+"</div> ";
		out = out.substr(0,out.length-2);
		document.getElementById(id).innerHTML=out;
		setTimeout(function(){CountDown(date,id)}, 1000);
	}
}
//]]>
</script>

<?php 
$list = $this->_getProducts();
$helper = Mage::helper('custom/data');
$uniqued = 'sm_custom_' . time() . rand();
$limit_header = $this->_getConfig('header_item');


if (!empty($list)) {?>
	
	

	<?php if( $this->_getConfig('custom_title_text') ){ ?>
		<div class="custom_title_text"><?php echo $this->_getConfig('custom_title_text','Custom Title'); ?></div>
	<?php } ?>
	<?php if ( $this->_getConfig('pretext') != null ) { ?>
		<div class="custom-pretext">
			<?php echo $this->_getConfig('pretext'); ?>
		</div>
	<?php } ?>

	<div id="<?php echo $uniqued; ?>" class="sm-custom-header">
		<div class="custom-items-header">
			<?php $count_item = 0; $j = 0; foreach ($list as $_product) { $j++; $count_item++;?>
			<?php 
				$specialPriceFromDate = $_product->start;
				$specialPriceToDate   = $_product->end;
				$today =  time();
				
				if( $today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate) ){ ?>

				<div class="custom-item">
					<div class="container">
						<div class="custom-content">
							<?php if( $_product->title ) { ?>
								<h3 class="custom-title">
									<a href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>" <?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?> >
										<?php echo $_product->title; ?>
									</a>
								</h3>
							<?php } ?>
							<?php if ( $_product->description ) { ?>
								<div class="custom-description">
									<?php echo $_product->description; ?>
								</div>
							<?php } ?>
						</div> 
						
						<div class="timer-custom">
							<div id="product_time_header_<?php echo $j;?>"></div>	
						</div>

						<script type="text/javascript">
						//<![CDATA[
							listdealheader.push('product_time_header_<?php echo $j."&&||&&".date("Y/m/d", strtotime($specialPriceToDate));?>') ;
						//]]>
						</script>	
					</div>
				</div>
				
				<?php if($count_item == $limit_header) break;?>
			<?php }}?>
		</div>
	</div>
	
	<script>
		jQuery(document).ready(function($) {
			var owl_custom_header = $(".custom-items-header");
			owl_custom_header.owlCarousel({
				animateOut: 'fadeOut',
				animateIn: 'fadeIn',
				items:1,
				autoplay:true,
				loop:false,
				nav : false,
				dots: false,				
				autoplaySpeed : 500,
				navSpeed : 500,
				dotsSpeed : 500,
				autoplayHoverPause: true,
				margin:0,
				
			});	 
		});	
	</script>	
	
	<?php if ($this->_getConfig('posttext') != null) { ?>
		<div class="custom-posttext"><?php echo $this->_getConfig('posttext'); ?></div>
	<?php } ?>

<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($){
	if(listdealheader.length > 0){
		for(i=0;i<listdealheader.length;i++)
		{
			var arr = listdealheader[i].split("&&||&&"); 
			var data = new Date(arr[1]);
			CountDown(data, arr[0]);
		}	
	}
});
//]]>
</script>	
<?php } else { echo $this->__('Has no content to show!'); }; ?>