<?php
/*------------------------------------------------------------------------
 # SM Listing Tabs - Version 2.0.1
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$helper = Mage::helper('listingtabs/data');
$list = $this->_getList();
$path_base = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
if (!empty($list)) {

	$import_str = "";
	$jsHelper = Mage::helper('core/js');
	// jquery has not added yet
	if (!defined('MAGENTECH_JQUERY') && (int)$this->_getConfig('include_jquery')) {
		// if module allowed jquery.
		$import_str .= $jsHelper->includeSkinScript('sm/listingtabs/js/jquery-1.8.2.min.js');
		$import_str .= $jsHelper->includeSkinScript('sm/listingtabs/js/jquery-noconflict.js');
		define('MAGENTECH_JQUERY', 1);
	}

	//$import_str .= $jsHelper->includeSkinScript('sm/listingtabs/js/owl.carousel.js');
	echo $import_str;

	$module_id = $this->_moduleID();
	$tag_id = 'sm_listing_tabs_' . rand() . time();
	$class_ltabs = 'ltabs00-' . $this->_getConfig('nbi_column1', 4) . ' ltabs01-' . $this->_getConfig('nbi_column1', 3) . ' ltabs02-' .
		$this->_getConfig('nbi_column2', 3) . ' ltabs03-' . $this->_getConfig('nbi-column3', 2) . ' ltabs04-' . $this->_getConfig('nbi-column4', 1);
	$show_loadmore_slider = $this->_getConfig('show_loadmore_slider');
	$class_show = ($show_loadmore_slider == 'loadmore') ? ' show-loadmore' : ' show-slider';
	if($show_loadmore_slider == 'none'){
		$class_show = 'show-loadmore no-control';
	}
	// view all
	$filter_type = $this->_getConfig('filter_type', 'categories');
	if($show_loadmore_slider == 'viewall'){
		$class_show = 'show-loadmore no-control show-viewall';
	}
	// list url view all
	$url_viewall_created_at = $this->_getConfig('url_viewall_created_at');
	$url_viewall_price = $this->_getConfig('url_viewall_price', '#');
	$url_viewall_lastest_product = $this->_getConfig('url_viewall_lastest_product', '#');
	$url_viewall_top_rating = $this->_getConfig('url_viewall_top_rating', '#');
	$url_viewall_most_reviewed = $this->_getConfig('url_viewall_most_reviewed', '#');
	$url_viewall_most_viewed = $this->_getConfig('url_viewall_most_viewed');
	$url_viewall_most_best_sales = $this->_getConfig('url_viewall_most_best_sales', '#');
	// end view all
	//effect
	$center = $this->_getConfig('center') == 1?'true':'false';
	$nav = $this->_getConfig('nav') == 1?'true':'false';
	$loop = $this->_getConfig('loop') == 1?'true':'false';
	$margin = (int)$this->_getConfig('margin') >= 0 ? $this->_getConfig('margin') : 5;
	$slideBy = (int)$this->_getConfig('slideBy') > 0 ? $this->_getConfig('slideBy') : 1;
	$autoplay = $this->_getConfig('autoplay') == 1?'true':'false';
	$autoplayHoverPause = $this->_getConfig('autoplayHoverPause') == 1?'true':'false';
	$autoplaySpeed = $this->_getConfig('autoplaySpeed') >= 0 ? $this->_getConfig('autoplaySpeed') : 5000;
	$navSpeed = $this->_getConfig('navSpeed') >= 0 ? $this->_getConfig('navSpeed') : 5000;
	$smartSpeed = $this->_getConfig('smartSpeed') >= 0 ? $this->_getConfig('smartSpeed') : 5000;
	$startPosition = $this->_getConfig('startPosition') > 0 ? $this->_getConfig('startPosition') : 1;
	$mouseDrag = $this->_getConfig('mouseDrag') == 1?'true':'false';
	$touchDrag = $this->_getConfig('touchDrag') == 1?'true':'false';
	$pullDrag = $this->_getConfig('pullDrag') == 1?'true':'false';

	$nb_column1 = $this->_getConfig('nbi_column1', 6);
	$nb_column2 = $this->_getConfig('nbi_column2', 6);
	$nb_column3 = $this->_getConfig('nbi_column3', 6);
	$nb_column4 = $this->_getConfig('nbi_column4', 6);

	?>
	<div id="<?php echo $tag_id; ?>" class="sj-listing-tabs first-load">
		<?php if ($this->_getConfig('listingtabs_title_text')) { ?>
			<div class="tab-listing-title">
				<?php echo $this->_getConfig('listingtabs_title_text', 'Tab Listing'); ?>
			</div>
		<?php
		}
		$pretext = $this->_getConfig('pretext');
		if (!empty($pretext)) {
			?>
			<div class="pre-text"><?php echo $this->_getConfig('pretext'); ?></div>
		<?php } ?>
		<div class="ltabs-wrap ">
			<div class="ltabs-tabs-container" data-delay="<?php echo $this->_getConfig('delay', 300); ?>"
			     data-duration="<?php echo $this->_getConfig('duration', 600); ?>"
			     data-effect="<?php echo $this->_getConfig('effect'); ?>"
			     data-ajaxurl="<?php echo Mage::getBaseUrl() . 'listingtabs/index/ajax'; ?>"
			     data-modid="<?php echo $tag_id; ?>">
				<!--Begin Tabs-->
				<?php include('default_tabs.phtml'); ?>
			</div>
			<!-- End Tabs-->
			<div class="ltabs-items-container <?php echo $class_show; ?>"><!--Begin Items-->
				<?php foreach ($list as $items) {

					$child_items = isset($items->child) ? $items->child : '';
					$cls_device = $class_ltabs;
					$cls_animate = $this->_getConfig('effect');
					$cls = (isset($items->sel) && $items->sel == "sel") ? ' ltabs-items-selected ltabs-items-loaded' : '';
					$cls .= ($items->id == "*") ? ' items-category-all' : ' items-category-' . $items->id;
					?>
					<div class="ltabs-items <?php echo $cls; ?>">
						<div class="products-grid ltabs-items-inner <?php echo $cls_device . ' ';
						echo $cls_animate; ?>">
							<?php if (!empty($child_items)) {
								include('default_items.php');
							} else {
								?>
								<div class="ltabs-loading"></div>
							<?php } ?>
						</div>

						<?php if($show_loadmore_slider == 'loadmore') { ?>
							<?php $classloaded = ($this->_getConfig('product_limitation', 2) >= $items->count || $this->_getConfig('product_limitation', 2) == 0) ? 'loaded' : '';?>
							<div class="ltabs-loadmore"
							     data-active-content=".items-category-<?php echo ($items->id == "*") ? 'all' : $items->id; ?>"
							     data-categoryid="<?php echo $items->id; ?>"
							     data-rl_start="<?php echo $this->_getConfig('product_limitation', 2) ?>"
							     data-rl_total="<?php echo $items->count ?>"
							     data-rl_allready="<?php echo $this->__('All ready'); ?>"
							     data-ajaxurl="<?php echo Mage::getBaseUrl() . 'listingtabs/index/ajax'; ?>"
							     data-modid="<?php echo $module_id; ?>"
							     data-rl_load="<?php echo $this->_getConfig('product_limitation', 2) ?>">
								<div class="ltabs-loadmore-btn <?php echo $classloaded ?>"
								     data-label=" <?php echo ($classloaded) ? $this->__('All ready') : $this->__('Load more'); ?>">
									<span class="ltabs-image-loading"></span>
								</div>
							</div>
						<?php } ?>
						<?php if($show_loadmore_slider == 'viewall') { ?>
							<div class="ltabs-viewall-btn">fghfhf
								<?php
								if($filter_type == 'categories') {
									$link_viewall = Mage::getModel("catalog/category")->load($items->id)->getUrl();
								} else {
									switch ($items->id) {
										case "created_at":
											$link_viewall = $url_viewall_created_at;
											break;
										case "price":
											$link_viewall = $url_viewall_price;
											break;
										case "lastest_product":
											$link_viewall = $url_viewall_lastest_product;
											break;
										case "top_rating":
											$link_viewall = $url_viewall_top_rating;
											break;
										case "most_reviewed":
											$link_viewall = $url_viewall_most_reviewed;
											break;
										case "most_viewed":
											$link_viewall = $url_viewall_most_viewed;
											echo $link_viewall;
											break;
										case "best_sales":
											$link_viewall = $url_viewall_most_best_sales;
											break;
										default:
											$link_viewall = "#";
									}	
									$link_viewall = $path_base.$link_viewall;
								}

								?>
								<a href="<?php echo $link_viewall ?>">Show all</a>
							</div>
						<?php } ?>	
					</div>
				<?php } ?>
			</div>
			<!--End Items-->
		</div>
		<?php
		$posttext = $this->_getConfig('posttext');
		if (!empty($posttext)) {
			?>
			<div class="post-text"><?php echo $this->_getConfig('posttext'); ?></div>
		<?php } ?>
	</div>

	<?php include('default_js.phtml'); ?>
<?php
} else {
	echo 'Has no item to show!';
} ?>



