<?php
/*------------------------------------------------------------------------
 # SM QuickView - Version 2.1.0
 # Copyright (c) 2015 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
if(!(int)Mage::getStoreConfig('quickview/general/active')) return;
$_cls = explode(',',  Mage::getStoreConfig('quickview/general/item_class'));
if(empty($_cls)) return;
$cls = array();
for($i = 0 ; $i < count($_cls) ; $i++) {
	$cls[] = trim($_cls[$i]);
}
$cls_str = implode(', ', $cls);
?>
 
<script type="text/javascript">
	//<![CDATA[
	jQuery(document).ready(function ($) {
	   function _SmQuickView(){	
			var	pathbase = 'quickview/index/view',
				_item_cls = $('<?php echo $cls_str ;?>'),
				_base_url = '<?php echo str_replace("index.php/","",$this->getUrl()) ?>',
				pathbase = 'quickview/index/view';
			var baseUrl = _base_url + pathbase;
			if(_item_cls.length > 0){
				_item_cls.each(function(index, el) {
					var $this = $(this)
					if($this.find("a.sm_quickview_handler").length <= 0){
						if( $this.find('a').length > 0 ){
							var _href =	$($this.find('a')[0]);				
							var	producturlpath = _href.attr('href').replace(_base_url,"");
								producturlpath = ( producturlpath.indexOf('index.php') >= 0 ) ? producturlpath.replace('index.php/','') : producturlpath;
							var	reloadurl = baseUrl+ ("/path/"+producturlpath).replace(/\/\//g,"/"),
								_quickviewbutton = "<a  data-toggle='tooltip' data-placement='top'  class='btn-action sm_quickview_handler' title='Quick View' href='"+reloadurl+"'><span class=''></span><span class='btn-text'><?php echo Mage::getStoreConfig('quickview/general/label_button') ;?></span></a>";
							$(el).append(_quickviewbutton);	
						}
					}
				});
			}
		}
		
		$('.sm_quickview_handler').fancybox({
			 width				: '<?php echo Mage::getStoreConfig('quickview/general/popup_width');?>',
			 height				: '<?php echo Mage::getStoreConfig('quickview/general/popup_height');?>',
			 autoSize			:  <?php echo Mage::getStoreConfig('quickview/general/auto_size'); ?>,
			 title				: 'null',
			 scrolling          : 'auto',
			 type				: 'iframe',
			 openEffect		    : '<?php echo Mage::getStoreConfig('quickview/general/open_effect') ;?>',
			 closeEffect		: '<?php echo Mage::getStoreConfig('quickview/general/close_effect'); ?>',
  			 helpers		    :{
					title:  null,
					<?php if((int)Mage::getStoreConfig('quickview/general/display_overlay')) { ?>
					overlay : {
						showEarly : true
					}
					<?php } else { ?>
					overlay: null
					<?php } ?>
			},
			beforeShow : function(){
			},
			afterShow		: function(){
			},
			beforeClose : function () {
			},
			afterClose : function(){
			}
		});
		
		setInterval(function(){ _SmQuickView(); } ,1000);
	});
	//]]>
</script>