<?php
/*------------------------------------------------------------------------
 # SM Twitter Slider - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getList();
?>

<?php if ($this->getConfig('pretext') != '') { ?>
    <div class="ts-pretext">
        <?php echo $this->getConfig('pretext'); ?>
    </div>
<?php } ?>

<div class="block block-twitter">
	<?php if ($this->getConfig('display_title') == 1 && $this->getConfig('title') != '') { ?>
		<div class="block-title">
			<strong>
				<span><?php echo $this->getConfig('title', 'Twitter slider'); ?></span>
			</strong>
		</div>
	<?php } ?>
	
	<div class="block-content">
			<?php if (!empty($list)) {
			echo $this->getScriptTags(); ?>

			<!--Begin sm-twitter-slider-->
			<div class="sm-twitter-slider">
				<script src="//platform.twitter.com/widgets.js" type="text/javascript"></script>
				<!--Begin ts-wrap-->
				<div class="ts-wrap">
					<?php
					$screen_label = '';
					foreach ($list as $_item) {
						$item = $_item;
						break;
					}
					$screen_label = $item->_username; ?>
					
					
					<!--Begin ts-slider-wrap-->
					<div class="ts-slider-wrap">
						<div class="ts-items">
							<?php foreach ($list as $item) {?>
								
								<div class="tw-item">
									<?php if ((int)$this->getConfig('display_avatars', 1)) {
										?>
										<div class="ts-header">
											<a title="<?php echo $item->_full_name; ?>" target="_blank" class="ts-avatar"
											   href="<?php echo $item->_twitter_link; ?>">
												<img src="<?php echo $item->_image; ?>" alt="<?php echo $item->_full_name; ?>"
													 title="<?php echo $item->_full_name; ?>">
											</a>

											<div class="ts-userinfo">
												<h2><?php echo $item->_full_name; ?></h2>
												<a target="_blank" href="<?php echo $item->_twitter_link; ?>">
													<?php echo $item->_username; ?>
												</a>
											</div>
										</div>
									<?php } ?>
									
									<div class="ts-item item">
										<div class="ts-text">
											<?php echo $item->_text; ?>
										</div>
										<div class="ts-btn">
											<a href="https://twitter.com/intent/tweet?in_reply_to=<?php echo $item->id_str; ?>"
											   target="_blank" class="reply-tweet">
												<?php echo $this->__('Reply'); ?>
											</a>
											<a href="https://twitter.com/intent/retweet?tweet_id=<?php echo $item->id_str; ?>"
											   class="retweet">
												<?php echo $this->__('Retweet'); ?>
											</a>
											<a href="https://twitter.com/intent/favorite?tweet_id=<?php echo $item->id_str; ?>"
											   class="favorite-tweet">
												<?php echo $this->__('Favorite'); ?>
											</a>
										</div>
									</div>
								</div>
							<?php
							} ?>
						</div>

					</div>
					<!--End ts-slider-wrap-->

					<?php
					if ((int)$this->getConfig('display_follow_button', 1)) {
						?>
						<!--Begin ts-btn-follow-->
						<div class="ts-btn-follow">
							<a href="https://twitter.com/<?php echo $screen_label; ?>" class="twitter-follow-button"
							   data-show-count="false">Follow @<?php echo $screen_label; ?></a>
							<script>!function (d, s, id) {
									var js, fjs = d.getElementsByTagName(s)[0];
									if (!d.getElementById(id)) {
										js = d.createElement(s);
										js.id = id;
										js.src = "https://platform.twitter.com/widgets.js";
										fjs.parentNode.insertBefore(js, fjs);
									}
								}(document, "script", "twitter-wjs");</script>
						</div>
						<!--End ts-btn-follow-->
					<?php } ?>
				</div>
				<!--End ts-wrap-->
			</div>
			<!--End sm-twitter-slider-->
		<?php } else { echo $this->__('Has no content to show!'); } ?>
	</div>
</div>



<?php if ($this->getConfig('posttext') != '') {
    ?>
    <div class="ts-posttext">
        <?php echo $this->getConfig('posttext'); ?>
    </div>
<?php } ?>
