<?php
/*------------------------------------------------------------------------
 # SM Twitter Slider - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getList();
$tag_id = 'sm_twitter_slider_' . rand() . time();

$play = (int)$this->getConfig('play', 1);

$interval = (int)$this->getConfig('interval', 4000);
$interval = ($play) ? $interval : 0;

$start = (int)$this->getConfig('start', 1);
$start = ($start <= 1 || $start >= count($list)) ? 0 : $start - 1;
$pause_hover = (int)$this->getConfig('pause_hover', 1);
$pause_hover = ($pause_hover == 0) ? '' : 'hover';

$effect = $this->getConfig('effect', 'slide');
$effect = ($effect == 'slide') ? 'slide' : '';

$slider_id = 'ts_slider_wap' . rand() . time();?>



<?php if ($this->getConfig('pretext') != '') { ?>
    <div class="ts-pretext">
        <?php echo $this->getConfig('pretext'); ?>
    </div>
<?php } ?>

<div class="block block-twitter">
	<?php if ($this->getConfig('display_title') == 1 && $this->getConfig('title') != '') { ?>
		<div class="block-title">
			<strong>
				<span><?php echo $this->getConfig('title', 'Twitter slider'); ?></span>
			</strong>
		</div>
		
		<div class="block-content">
			<?php if (!empty($list)) {
			echo $this->getScriptTags(); ?>

			<!--Begin sm-twitter-slider-->
			<div id="<?php echo $tag_id; ?>" class="sm-twitter-slider">
				<script src="//platform.twitter.com/widgets.js" type="text/javascript"></script>
				<!--Begin ts-wrap-->
				<div class="ts-wrap">
					<?php
					$screen_label = '';
					foreach ($list as $_item) {
						$item = $_item;
						break;
					}
					$screen_label = $item->_username;
					if ((int)$this->getConfig('display_avatars', 1)) {
						?>
						<div class="ts-header">
							<a title="<?php echo $item->_full_name; ?>" target="_blank" class="ts-avatar"
							   href="<?php echo $item->_twitter_link; ?>">
							<span class="ts-mask">
								<span class="ts-mask-logo">Open in Twitter</span>
							</span>
								<img src="<?php echo $item->_image; ?>" alt="<?php echo $item->_full_name; ?>"
									 title="<?php echo $item->_full_name; ?>">
							</a>

							<div class="ts-userinfo">
								<h2><?php echo $item->_full_name; ?></h2>
								<a target="_blank" href="<?php echo $item->_twitter_link; ?>">
									<?php echo $item->_username; ?>
								</a>
							</div>
						</div>
					<?php
					} ?>
					<!--Begin ts-slider-wrap-->
					<div class="ts-slider-wrap <?php echo $effect; ?>" id="<?php echo $slider_id; ?>"
						 data-interval="<?php echo $interval; ?>" data-pause="<?php echo $pause_hover; ?>"
						>
						<div class="ts-items">
							<?php $j = -1;
							foreach ($list as $item) {
								$j++; //var_dump(count($list));
								?>
								<?php $active_cls = ($j == $start) ? 'active' : ''; ?>
								<div class="ts-item item <?php echo $active_cls; ?>">
									<div class="ts-text">
										<?php echo $item->_text; ?>
									</div>
									<div class="ts-btn">
										<a href="https://twitter.com/intent/tweet?in_reply_to=<?php echo $item->id_str; ?>"
										   target="_blank" class="reply-tweet">
											<?php echo $this->__('Reply'); ?>
										</a>
										<a href="https://twitter.com/intent/retweet?tweet_id=<?php echo $item->id_str; ?>"
										   class="retweet">
											<?php echo $this->__('Retweet'); ?>
										</a>
										<a href="https://twitter.com/intent/favorite?tweet_id=<?php echo $item->id_str; ?>"
										   class="favorite-tweet">
											<?php echo $this->__('Favorite'); ?>
										</a>
									</div>
									<div class="ts-created">
										<a href="https://twitter.com/smartaddons/status/<?php echo $item->id_str; ?>"
										   target="_blank" title="<?php echo $item->_full_name; ?>">
											<?php echo date('j F Y', strtotime($item->created_at)); ?>
										</a>
									</div>
								</div>
							<?php
							} ?>
						</div>

						<!--Begin ts-control-->
						<div class="ts-control">
							<?php
							if ((int)$this->getConfig('display_direction_button', 1)) {
								?>
								<a class="ts-ctr-prev ts-ctr" href="#<?php echo $slider_id; ?>" data-jslide="prev">&lsaquo;</a>
							<?php } ?>
							<ul class="ts-ctr-pages">
								<?php $k = -1;
								$pags = count($list);
								for ($i = 0; $i < $pags; $i++) {
									$k++;
									$sel_class = $k == $start ? " sel" : ""; ?>
									<li class="ts-ctr-page <?php echo $sel_class; ?>" href="#<?php echo $slider_id; ?>"
										data-jslide="<?php echo $k; ?>">
									</li>
								<?php } ?>
							</ul>
							<?php
							if ((int)$this->getConfig('display_direction_button', 1)) {
								?>
								<a class="ts-ctr-next ts-ctr" href="#<?php echo $slider_id; ?>" data-jslide="next">&rsaquo;</a>
							<?php } ?>
						</div>
						<!--End ts-control-->

					</div>
					<!--End ts-slider-wrap-->

					<?php
					if ((int)$this->getConfig('display_follow_button', 1)) {
						?>
						<!--Begin ts-btn-follow-->
						<div class="ts-btn-follow">
							<a href="https://twitter.com/<?php echo $screen_label; ?>" class="twitter-follow-button"
							   data-show-count="false">Follow @<?php echo $screen_label; ?></a>
							<script>!function (d, s, id) {
									var js, fjs = d.getElementsByTagName(s)[0];
									if (!d.getElementById(id)) {
										js = d.createElement(s);
										js.id = id;
										js.src = "https://platform.twitter.com/widgets.js";
										fjs.parentNode.insertBefore(js, fjs);
									}
								}(document, "script", "twitter-wjs");</script>
						</div>
						<!--End ts-btn-follow-->
					<?php } ?>
				</div>
				<!--End ts-wrap-->
			</div>
			<!--End sm-twitter-slider-->
		<?php } else { echo $this->__('Has no content to show!'); } ?>
		</div>
	<?php } ?>
</div>



<?php if ($this->getConfig('posttext') != '') {
    ?>
    <div class="ts-posttext">
        <?php echo $this->getConfig('posttext'); ?>
    </div>
<?php } ?>
<script type="text/javascript">
    //<![CDATA[
    jQuery(document).ready(function ($) {
        ;
        (function (element) {
            var $element = $(element);
            var $_slider = $('#<?php echo $slider_id; ?>', $element);
            $_slider.each(function () {
                var $this = $(this), options = options = !$this.data('modal') && $.extend({}, $this.data());
                $this.jcarousel(options);
                $this.bind('jslide', function (e) {
                    var index = $(this).find(e.relatedTarget).index();
                    $('[data-jslide]').each(function () {
                        var $nav = $(this), $navData = $nav.data(), href, $target = $($nav.attr('data-target') || (href = $nav.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, ''));
                        if (!$target.is($this)) return;
                        if (typeof $navData.jslide == 'number' && $navData.jslide == index) {
                            $nav.addClass('sel');
                        } else {
                            $nav.removeClass('sel');
                        }
                    });
                });
                <?php
                if($this->getConfig('swipe_enable') == 1) {	?>
                $this.touchSwipeLeft(function () {
                        $this.jcarousel('next');
                    }
                );
                $this.touchSwipeRight(function () {
                        $this.jcarousel('prev');
                    }
                );
                <?php } ?>
                return;
            });

        })('#<?php echo $tag_id; ?>');
    });
    //]]>
</script>