<?php
/*------------------------------------------------------------------------
 # SM Shop By - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
?>

<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');

$config = Mage::helper('topshop/config');
$effect_style = $config->getProductListing('effect_style');
$display_nav = $config->getProductListing('show_nav');
$display_dot = $config->getProductListing('show_dot');
$limit = $config->getProductListing('slide_limit');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php if (!$this->getRequest()->isAjax()): ?>
        <div id="ajax-errors" style="display: none;">
            <ul class="messages">
                <li class="error-msg">
                    <ul>
                        <li><span><?php echo $this->__('An error occurred, please try again later.'); ?></span></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div id="loading" style="display: none; margin-bottom: 10px; text-align: center;">
            <img class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/loading-qv.gif'); ?>">
        </div>

	<div id="catalog-listing">
    <?php endif; ?>
		<div class="category-products">
			<div class="wow fadeInUp">
			<?php echo $this->getToolbarHtml() ?>
			</div>
			
			<?php // List mode ?>
			<?php if ($this->getMode() != 'grid'): ?>
				<?php $_iterator = 0; ?>
				<ol class="products-list" id="products-list">
					<?php foreach ($_productCollection as $_product): ?>
					<li class="item respl-item-list">
						<div class="wow fadeInUp">
						<div class="item-inner">
							<div class="box-image-list">
									<?php
										$url_product = $_product->getProductUrl();
									?>
									
									<?php if($effect_style == 'default'){?>
									<div class="effect-default">
										<a href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
											<img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</a>
									</div>
									<?php } else if($effect_style == 'thumbs'){?>
									<div class="effect-thumbs">
										<a href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
											<img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											<?php if($_product->getThumbnail() != $_product->getSmallImage()) { ?> 
												<img class="second-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(270, 320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											<?php } ?>
										</a>
									</div>
									<?php } else if($effect_style == 'slider'){?>
									<div class="effect-slider">
										<div class="image-slider-product">
											<div class="slider-img-thumb">
												<?php $_media = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();?>
												<?php $i=0; foreach($_media as $_img){ $i++;?>
													<div class="item_img">
														<a href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
															<img  src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_img->getFile())->resize(270,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
														</a>
													</div>
													<?php if($i == $limit && $limit != 0) break;?>
												<?php } ?>
											</div>
										</div>
										
										
									</div>
									<?php } ?>
								
								<?php
									// Provides extra blocks on which to hang some features for products in the list
									// Features providing UI elements targeting this block will display directly below the product name
									if ($this->getChild('name.after')) {
										$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
										foreach ($_nameAfterChildren as $_nameAfterChildName) {
											$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
											$_nameAfterChild->setProduct($_product);
											echo $_nameAfterChild->toHtml();
										}
									}
								?>
								
									<!--LABEL PRODUCT-->
									<?php
									$id_product = Mage::getModel('catalog/product')->load($_product->getId());
									$specialprice = $id_product->getSpecialPrice();
									$specialPriceFromDate = $id_product->getSpecialFromDate();
									$specialPriceToDate = $id_product->getSpecialToDate();
									$today = time();

									if ($specialprice) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
											<div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php echo $this->__('Sale'); ?>
												</span>
											</div>
										<?php }
									}?>


									<?php
									$now = date("Y-m-d");
									$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
									$newsTo = substr($_product->getData('news_to_date'), 0, 10);
									if ($newsTo != '' || $newsFrom != '') {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
												<div class="label-product label-new">
													<span class="new-product-icon"><?php echo $this->__('New'); ?></span>
												</div>
										<?php }
									} ?>
									
									<!--END LABEL PRODUCT-->
									
							</div>
							
							<div class="box-info-list">
								<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
								<h2 class="product-name">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
								</h2>
								
								<?php echo $this->getReviewsSummaryHtml($_product, "short", true); ?>
								
								<?php echo $this->getPriceHtml($_product, true) ?>
								
								<div class="desc std">
									<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								</div>
								
								<div class="actions">
									<a style="display:none;" href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
									<?php if($_product->isSaleable()): ?>
										<button class="btn-action btn-cart" type="button" title="<?php echo $this->__('Add to Cart') ?>"  onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
											<span>
												<span><?php echo $this->__('Add to Cart') ?></span>
											</span>
										</button>
									<?php else: ?>
											<p class="btn-action btn-cart availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
									
									<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<a data-toggle="tooltip" data-placement="top" class="btn-action link-compare" title="<?php echo $this->__('Compare') ?>" href="<?php echo $_compareUrl ?>" >
												<span><?php echo $this->__('Compare') ?></span>
											</a>
									<?php endif; ?>
										
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<a data-toggle="tooltip" data-placement="top" class="btn-action link-wishlist" title="<?php echo $this->__('Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" >
												<span class="btn-text"><?php echo $this->__('Wishlist') ?></span>
											</a>
									<?php endif; ?>
								</div>
							</div>
							<div class="clearer"></div>
						</div>
						</div>
					</li>
					<?php endforeach; ?>
				</ol>
				<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

			<?php else: ?>

			<?php // Grid Mode ?>

			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $this->getColumnCount(); ?>
				<div class="products-grid-wrapper">
				<ul class="products-grid">
					<?php $i = 0;
					foreach ($_productCollection as $_product): ?>
					<?php if ($i++ % $_columnCount == 0): ?>

					<?php endif ?>
						<li class="item">
							<div class="wow fadeInUp">
							<div class="item-inner">
								<div class="box-image">
									<?php
										$url_product = $_product->getProductUrl();
									?>
									
									<?php if($effect_style == 'default'){?>
									<div class="effect-default">
										<a href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
											<img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</a>
									</div>
									<?php } else if($effect_style == 'thumbs'){?>
									<div class="effect-thumbs">
										<a href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
											<img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											<?php if($_product->getThumbnail() != $_product->getSmallImage()) { ?> 
												<img class="second-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(270, 320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											<?php } ?>
										</a>
									</div>
									<?php } else if($effect_style == 'slider'){?>
									<div class="effect-slider">
										<div class="image-slider-product">
											<div class="slider-img-thumb">
												<?php $_media = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();?>
												<?php $i=0; foreach($_media as $_img){ $i++;?>
													<div class="item_img">
														<a href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
															<img  src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_img->getFile())->resize(270,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
														</a>
													</div>
													<?php if($i == $limit && $limit != 0) break;?>
												<?php } ?>
											</div>
										</div>
										
										
									</div>
									<?php } ?>

									<div class="bottom-action-out-wrap">
										<div class="bottom-action-out">
											<div class="bottom-action">
												<a style="display:none;" href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
												<?php if($_product->isSaleable()): ?>
													<button class="btn-action btn-cart" type="button" title="<?php echo $this->__('Add to Cart') ?>"  onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
														<span>
															<span><?php echo $this->__('Add to Cart') ?></span>
														</span>
													</button>
												<?php else: ?>
														<p class="btn-action btn-cart availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
												<?php endif; ?>
												
												<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
														<a data-toggle="tooltip" data-placement="top" class="btn-action link-compare" title="<?php echo $this->__('Compare') ?>" href="<?php echo $_compareUrl ?>" >
															<span><?php echo $this->__('Compare') ?></span>
														</a>
												<?php endif; ?>
													
												<?php if ($this->helper('wishlist')->isAllow()) : ?>
														<a data-toggle="tooltip" data-placement="top" class="btn-action link-wishlist" title="<?php echo $this->__('Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" >
															<span class="btn-text"><?php echo $this->__('Wishlist') ?></span>
														</a>
												<?php endif; ?>
											</div>
										</div>
									</div>

									<?php
										// Provides extra blocks on which to hang some features for products in the list
										// Features providing UI elements targeting this block will display directly below the product name
										if ($this->getChild('name.after') && $effect_style != 'slider') {
											$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
											foreach ($_nameAfterChildren as $_nameAfterChildName) {
												$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
												$_nameAfterChild->setProduct($_product);
												echo $_nameAfterChild->toHtml();
											}
										}
									?>
									
									<!--LABEL PRODUCT-->
									<?php
									$id_product = Mage::getModel('catalog/product')->load($_product->getId());
									$specialprice = $id_product->getSpecialPrice();
									$specialPriceFromDate = $id_product->getSpecialFromDate();
									$specialPriceToDate = $id_product->getSpecialToDate();
									$today = time();

									if ($specialprice) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
											<div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php echo $this->__('Sale'); ?>
												</span>
											</div>
										<?php }
									}?>


									<?php
									$now = date("Y-m-d");
									$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
									$newsTo = substr($_product->getData('news_to_date'), 0, 10);
									if ($newsTo != '' || $newsFrom != '') {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
												<div class="label-product label-new">
													<span class="new-product-icon"><?php echo $this->__('New'); ?></span>
												</div>
										<?php }
									} ?>
									
									<!--END LABEL PRODUCT-->
								
								</div>
								
								<div class="box-info">
									<h2 class="product-name">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
									</h2>

									<?php echo $this->getReviewsSummaryHtml($_product, "short", true); ?>

									<?php echo $this->getPriceHtml($_product, true) ?>

								</div>

								
							</div>
							</div>
						</li>
						<?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>

					<?php endif ?>
					<?php endforeach ?>
				</ul>
				</div>
				<script
					type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
			<?php endif; ?>

			<div class="wow fadeInUp">
				<div class="toolbar-bottom">
					<?php echo $this->getToolbarHtml() ?>
				</div>
			</div>
			
			<?php
			// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
			if ($this->getChild('after') && $effect_style != 'slider') {
				$_afterChildren = $this->getChild('after')->getSortedChildren();
				foreach ($_afterChildren as $_afterChildName) {
					$_afterChild = $this->getChild('after')->getChild($_afterChildName);
					//set product collection on after blocks
					$_afterChild->setProductCollection($_productCollection);
					echo $_afterChild->toHtml();
				}
			}
			?>
										
		</div>
    <?php if (!$this->getRequest()->isAjax()): ?>
    </div>
    <?php endif; ?>
<?php endif; ?>


<?php if ($this->helper('sm_shopby')->isAjaxEnabled() && !$this->getRequest()->isAjax()): ?>
    <script type="text/javascript">
        //<![CDATA[
        function pushState(data, link, replace) {
            var History = window.History;
            if (!History.enabled) {
                return false;
            }

            if (replace) {
                History.replaceState(data, document.title, link);
            } else {
                History.pushState(data, document.title, link);
            }
        }

        function handleEvent(el, event) {
            var url, fullUrl;
            if (typeof el === 'string') {
                url = el;
            } else if (el.tagName.toLowerCase() === 'a') {
                url = $(el).readAttribute('href');
            } else if (el.tagName.toLowerCase() === 'select') {
                url = $(el).getValue();
            }

            <?php // Add this to query string for full page caching systems ?>
            if (url.indexOf('?') != -1) {
                fullUrl = url + '&isLayerAjax=1';
            } else {
                fullUrl = url + '?isLayerAjax=1';
            }

            $('loading').show();
            $('ajax-errors').hide();

            pushState(null, url, false);

            new Ajax.Request(fullUrl, {
                method: 'get',
                onSuccess: function (transport) {
                    if (transport.responseJSON) {
                        $('catalog-listing').update(transport.responseJSON.listing);
						if($('layered-navigation')){
							$('layered-navigation').update(transport.responseJSON.layer);
						}
                        pushState({
                            listing: transport.responseJSON.listing,
                            layer: transport.responseJSON.layer
                        }, url, true);
						ConfigurableSwatchesList.init();
                        ajaxListener();
                    } else {
                        $('ajax-errors').show();
                    }
                    $('loading').hide();
					if (typeof ajaxCartPro !== 'undefined') {
						ajaxCartPro.eventForWishlist();
						ajaxCartPro.eventForCompare();
					}
                }
				
            });

            if (event) {
                event.preventDefault();
            }
        }
        function ajaxListener() {
            var els;
            els = $$('div.pager a').concat(
                $$('div.category-products div.sort-by a'),
                $$('div.category-products div.sorter a'),
                $$('div.category-products div.pager select'),
                $$('div.category-products div.limiter select'),
                $$('div.category-products div.sort-by select'),
                $$('div.block-layered-nav a')
            );
            els.each(function (el) {
                if (el.tagName.toLowerCase() === 'a') {
                    $(el).observe('click', function (event) {
                        handleEvent(this, event);
                    });
                } else if (el.tagName.toLowerCase() === 'select') {
                    $(el).setAttribute('onchange', '');
                    $(el).observe('change', function (event) {
                        handleEvent(this, event);
                    });
                }
            });
        }
        document.observe("dom:loaded", function () {
            ajaxListener();

            (function (History) {
                if (!History.enabled) {
                    return false;
                }

                pushState({
                    listing: $('catalog-listing').innerHTML,
                    layer: $('layered-navigation').innerHTML
                }, document.location.href, true);

                // Bind to StateChange Event
                History.Adapter.bind(window, 'popstate', function (event) {
                    if (event.type == 'popstate') {
                        var State = History.getState();
                        $('catalog-listing').update(State.data.listing);
                        $('layered-navigation').update(State.data.layer);
                        ajaxListener();
                    }
                });
            })(window.History);
        });
        //]]>
    </script>

<?php endif; ?>

<?php if($this->getRequest()->isAjax()){?>
		<script type="text/javascript">
			jQuery.noConflict()
				jQuery(".slider-img-thumb").lightSlider({
					loop: false,
					vertical:false,
					slideMargin: 0,
					item: 1,

					<?php if($display_nav){?>
						controls : true, // Show next and prev buttons
					<?php } else { ?>
						controls : false,
					<?php } ?>
														
					<?php if($display_dot){?>
						pager: true,
					<?php } else {?>
						pager: false,
					<?php } ?>
				});  

		</script>
<?php } ?>


