<?php
/*------------------------------------------------------------------------
 # SM Deal - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<script type="text/javascript">
//<![CDATA[
data = new Date(2013,10,26,12,00,00);
var listdeal = [];
function CountDown(date,id){
	dateNow = new Date();
	amount = date.getTime() - dateNow.getTime();
	delete dateNow;
	if(amount < 0){
		document.getElementById(id).innerHTML="Now!";
	} else{
		days=0;hours=0;mins=0;secs=0;out="";
		amount = Math.floor(amount/1000);
		days=Math.floor(amount/86400);
		amount=amount%86400;
		hours=Math.floor(amount/3600);
		amount=amount%3600;
		mins=Math.floor(amount/60);
		amount=amount%60;
		secs=Math.floor(amount);
		if(days != 0){out += "<div class='time-item time-day'>" + "<div class='num-time'>" + days + "</div>" +" <div class='name-time'>"+((days==1)?"day":"days") + "</div>"+"</div> ";}
		if(hours != 0){out += "<div class='time-item time-hour'>" + "<div class='num-time'>" + hours + "</div>" +" <div class='name-time'>"+((hours==1)?"":"") + "</div>"+"</div> ";}
		out += "<div class='time-item time-min'>" + "<div class='num-time'>" + mins + "</div>" +" <div class='name-time'>"+((mins==1)?"":"") + "</div>"+"</div> ";
		out += "<div class='time-item time-sec'>" + "<div class='num-time'>" + secs + "</div>" +" <div class='name-time'>"+((secs==1)?"":"") + "</div>"+"</div> ";
		out = out.substr(0,out.length-2);
		document.getElementById(id).innerHTML=out;
		setTimeout(function(){CountDown(date,id)}, 1000);
	}
}
//]]>
</script>



<?php 
$list = $this->_getProducts();
$helper = Mage::helper('deal/data');

$config = Mage::helper('topshop/config');
$effect_style = $config->getProductListing('effect_style');
$display_nav = $config->getProductListing('show_nav');
$display_dot = $config->getProductListing('show_dot');

if (!empty($list)) { 
	$config = Mage::helper('topshop/config');

	$effect_style = $config->getProductListing('effect_style');
	$display_nav = $config->getProductListing('show_nav');
	$display_dot = $config->getProductListing('show_dot');

	$nb_column1 = $this->_getConfig('nb_column1', 6);
	$nb_column2 = $this->_getConfig('nb_column2', 4);
	$nb_column3 = $this->_getConfig('nb_column3', 2);
	$nb_column4 = $this->_getConfig('nb_column4', 1);
	$imgcfg_width = $this->_getConfig('imgcfg_width', 250);
	$imgcfg_height = $this->_getConfig('imgcfg_height', 296);

?>

<?php if ( $this->_getConfig('pretext') != null ) { ?>
	<div class="deal-pretext">
		<?php echo $this->_getConfig('pretext'); ?>
	</div>
<?php } ?>

<div class="deal-wrapper">
	<div class="deal-wrapper-inner">
		<div class="title-home">
			<h2><?php echo $this->_getConfig('deal_title_text','Deal Title'); ?></h2>
		</div>
		

			<div class="deal-slider products-grid">
				<?php  
				$j = 0;
				$_limit = (int)$this->_getConfig('product_limitation', 5);		
				if ( $_limit <= 0 ){
					$_limit = count($list);
				}
				foreach ($list as $_product) {
					
				$specialPriceFromDate = $_product->special_from_date;
				$specialPriceToDate = $_product->special_to_date;
				$today =  time();
				$dayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);	
				
				if ($specialPriceFromDate && $specialPriceToDate){
					if( $today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate) ){
					$specialprice = $_product->special_price;					
					$j++;
					if( $j <= $_limit && $specialprice){
					?>			
					<div class="item">
						<div class="item-inner">
						
							<?php if ( $_product->_image && $this->_getConfig('product_image_display') ) { ?>
							<div class="box-image">

								<?php
									$url_product = $_product->link;
								?>
									
								<?php if($effect_style == 'default'){?>
									<div class="effect-default">
										<a href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
											<img src="<?php echo $_product->_image; ?>" alt="<?php echo $_product->title; ?>" />
										</a>
									</div>
								<?php } else if($effect_style == 'thumbs'){?>
									<div class="effect-thumbs">
										<a href="<?php echo $url_product ?>" title="<?php echo $_product->title; ?>" class="product-image">
											<img src="<?php echo $_product->_image; ?>" alt="<?php echo $_product->title; ?>" />
											<?php if($_product->getThumbnail() != $_product->getSmallImage()) { ?> 
												<img class="second-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($imgcfg_width, $imgcfg_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											<?php } ?>
										</a>
									</div>
								<?php } else if($effect_style == 'slider'){?>
									<div class="effect-slider">
										<div class="image-slider-product">
											<div class="slider-img-thumb">
												<?php $_media = Mage::getModel('topshop/product')->load($_product->getId())->getMediaGalleryImages();?>
												<?php foreach($_media as $_img): ?>
													<div class="item_img">
														<a href="<?php echo $url_product ?>" title="<?php echo $_product->title; ?>">
															<img  src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_img->getFile())->resize($imgcfg_width, $imgcfg_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
														</a>
													</div>
												<?php endforeach; ?>
											</div>
										</div>
										
										
									</div>
								<?php } ?>
								<div class="bottom-action-out-wrap">
									<div class="bottom-action-out">	
										<div class="bottom-action">
											<a style="display:none;" href="<?php echo $url_product ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" ></a>
											<?php if ((int)$this->_getConfig('product_addcart_display', 1)) : ?>
												<?php if ($_product->isSaleable()): ?>
													<button class="btn-action btn-cart" type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
														<span>
															<span><?php echo $this->__('Add to Cart') ?></span>
														</span>
													</button>
												<?php else: ?>
													<p class="availability out-of-stock">
														<span><?php echo $this->__('Out of stock') ?></span>
													</p>
												<?php endif;
											endif;
											if ((int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) :?>
												<?php if ($_compareUrl = $this->getAddToCompareUrl($_product) && (int)$this->_getConfig('product_addcompare_display', 1)): ?>
													<a data-toggle="tooltip" data-placement="top" class="btn-action link-compare" title="<?php echo $this->__('Compare') ?>" href="<?php echo $this->getAddToCompareUrl($_product) ?>" >
														<span><?php echo $this->__('Compare') ?></span>
													</a>
												<?php endif; ?>
												
												<?php if ($this->helper('wishlist')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1)) : ?>
													<a data-toggle="tooltip" data-placement="top" class="btn-action link-wishlist" title="<?php echo $this->__('Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" >
														<span><?php echo $this->__('Wishlist') ?></span>
													</a>
												<?php endif; ?>
											<?php endif; ?>
										</div>								
									</div>
								</div>

								
									<!--LABEL PRODUCT-->
										<?php
										$id_product = Mage::getModel('catalog/product')->load($_product->getId());
										$specialprice = $id_product->getSpecialPrice();
										$today = time();

										if ($specialprice) {
											if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
												<div class="label-product label-sale">
													<span class="sale-product-icon">
														<?php echo $this->__('Sale'); ?>
													</span>
												</div>
											<?php }
										}?>


										<?php
										$now = date("Y-m-d");
										$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
										$newsTo = substr($_product->getData('news_to_date'), 0, 10);
										if ($newsTo != '' || $newsFrom != '') {
											if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
													<div class="label-product label-new">
														<span class="new-product-icon"><?php echo $this->__('New'); ?></span>
													</div>
											<?php }
										} ?>
										
									<!--END LABEL PRODUCT-->
								
							</div>
							<?php } ?>
							
							
						
							<div class="box-info">
								<?php if( (int)$this->_getConfig('product_title_display',1) ) { ?>
									<h2 class="product-name">
										<a href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>"
											<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
											>
											<?php echo $helper->truncate($_product->title,$this->_getConfig('product_title_maxlength'));?>
										</a>
									</h2>
								<?php } ?>

								<?php if ( (int)$this->_getConfig('product_description_display', 1) ) { ?>
									<div class="deal-description">
										<?php echo $_product->_description; ?>
									</div>
								<?php } ?>

								<?php if ($this->_getConfig('item_date_display') == 1) { ?>
									<div class="deal-date">
										<?php  echo  $_product->created_at; ?>
									</div>
								<?php } ?>

								<?php if ( (int)$this->_getConfig('product_reviews_count', 1) ) { ?>
									<div class="deal-review">
										<?php echo $this->getReviewsSummaryHtml($_product, 'short', true); ?>
									</div>
								<?php } ?>

								<?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
									<div class="deal-price">
										<div class="sale-price">
											<?php echo $this->getPriceHtml($_product, true); ?>
										</div>
									</div>
								<?php } ?>

								<?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
									<div class="deal-detail">
										<a href="<?php echo $_product->link ?>"
										   title="<?php echo $_product->title; ?>"
											<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
											>
											<?php echo $this->_getConfig('product_readmore_text','Details'); ?>
										</a>
									</div>
								<?php } ?>
							</div> 
							
							<div class="timer-deal">
								<div class="timer-product">
									<div id="product_time_sidebar_<?php echo $j;?>"></div>	
								</div>
							</div>
							<script type="text/javascript">
							//<![CDATA[
								listdeal.push('product_time_sidebar_<?php echo $j."&&||&&".date("Y/m/d", strtotime($specialPriceToDate));?>') ;
							//]]>
							</script>
							
						</div>
					</div>

					<?php }}} ?>
				<?php } ?>
			</div>
	</div>
	<?php if ( $this->_getConfig('posttext') != null ) { ?>
		<div class="deal-posttext">
			<?php $id_static = $this->_getConfig('posttext'); ?>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($id_static)->toHtml(); ?>
		</div>
	<?php } ?>		
</div>

	<script>
		jQuery(document).ready(function($) {
			var owl_deal = $(".deal-slider");
			owl_deal.owlCarousel({
				responsive:{
					0:{
						items:1
					},
					480:{
						items:<?php echo $nb_column4;?>
					},
					768:{
						items:<?php echo $nb_column3;?>
					},
					992:{
						items:<?php echo $nb_column2;?>
					},
					1200:{
						items:<?php echo $nb_column1;?>
					}
				},
					
				autoplay:false,
				loop:false,
				nav : true,
				dots: false,
				autoplaySpeed : 500,
				navSpeed : 500,
				dotsSpeed : 500,
				autoplayHoverPause: true,
				margin:30,
				
			});	 
		});	
	</script>	



<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($){
	if(listdeal.length > 0){
		for(i=0;i<listdeal.length;i++)
		{
			var arr = listdeal[i].split("&&||&&"); 
			var data = new Date(arr[1]);
			CountDown(data, arr[0]);
		}	
	}
});
//]]>
</script>	
<?php } else { echo $this->__('Has no content to show!'); }; ?>