<?php
/*------------------------------------------------------------------------
 # SM Super Categories - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$image_base = Mage::getModel('catalog/product')->getSmallImageUrl();
$helper = Mage::helper('supercategories/data');
$cat_info = $this->getListCategoriesFilter();
$list = $this->getListCriterionFilter();

if (!empty($list)) {
	$stop = (int)$this->_getConfig('stop',1) ? 'hover' : '';
	$play = (int)$this->_getConfig('play',1);
	$interval = (int)$this->_getConfig('delay');
	$interval = $play ? $interval : 0;
	$speed =(int)$this->_getConfig('duration');
	$start = (int) $this->_getConfig('start');
	$start = ( $start <= 0 || $start > count($list) ) ? 0 : $start - 1;
	$step = (int)$this->_getConfig('scroll',1);
	$step = $step <= 0 ? 1: $step;
	$posttext = $this->_getConfig('posttext');
	$item_page = (int)$this->_getConfig('product_limitation_a_slider',6);

	$instance = rand() . time();
	$tag_id = 'sm_listing_tabs_' . rand() . time();
	$uniqued ='cat_slider_'.rand().time();
	$class_ltabs = 'ltabs00-' . $this->_getConfig('nbi_column1', 4) . ' ltabs01-' . $this->_getConfig('nbi_column1', 3) . ' ltabs02-' . $this->_getConfig('nbi_column2', 3) . ' ltabs03-' . $this->_getConfig('nbi_column3', 2) . ' ltabs04-' . $this->_getConfig('nbi_column4', 1);
	$show_loadmore_slider = $this->_getConfig('show_loadmore_slider');
	$class_show = ($show_loadmore_slider == 'loadmore') ? ' show-loadmore' : ' show-slider';
	if($show_loadmore_slider == 'none'){
		$class_show = 'show-loadmore no-control';
	}
	$width = (int)$this->_getConfig('img_cat_width');
	$width = $width ? 'width:'.$width.'px;' : '';
	$height = (int)$this->_getConfig('img_cat_height');
	$height = $height ? 'height:'.$height.'px;' : '';

	$style_img = 'style="'.$width.' '.$height.'"';
	
	$nb_column1 = $this->_getConfig('nbi_column1', 6);
	$nb_column2 = $this->_getConfig('nbi_column2', 6);
	$nb_column3 = $this->_getConfig('nbi_column3', 6);
	$nb_column4 = $this->_getConfig('nbi_column4', 6);	
	$product_limitation_start = $this->_getConfig('product_limitation', 5)
	?>
	<?php $class_respl = 'preset01-' . $this->_getConfig('nb_column1', 4) . ' preset02-' . $this->_getConfig('nb_column2', 3) . ' preset03-' . $this->_getConfig('nb_column3', 2) . ' preset04-' . $this->_getConfig('nb_column4', 2) . ' preset05-' . $this->_getConfig('nb_column5', 1); ?>
	<!--[if lt IE 9]>
	<div id="<?php echo $tag_id; ?>" class="sj-listing-tabs msie lt-ie9 first-load"><![endif]-->
	<!--[if IE 9]>
	<div id="<?php echo $tag_id; ?>" class="sj-listing-tabs msie first-load"><![endif]-->
	<!--[if gt IE 9]><!-->
	<div id="<?php echo $tag_id; ?>" class="sj-listing-tabs first-load"><!--<![endif]-->
		
		<div class="category-wrap"> 
		
			<?php 
			/*echo "<pre>";
			var_dump($cat_info);
			die();*/
			
			foreach( $cat_info as $cat){
				if(isset($cat['child']))
					$cat_child = $cat['child'];
				else
					$cat_child = null;
			?>
				<div class="title-home">
					<h2><?php echo $cat['name'];?></h2>
				</div>
				
				<?php if( $cat_child != null ){?>
				<div id="<?php echo $uniqued; ?>" class="container-slider">
				<?php if( $this->_getConfig('next_prev_display', 1) == 1 ){?>
					<ul class="control-button">
						<li class="preview"></li>
						<li class="next"></li>
					</ul>		
				<?php }?>	
					<div class="slider not-js cols-6 <?php echo $class_respl;?>">
						<div class="vpo-wrap">
							<div class="vp">
								<div class="vpi-wrap">
								<?php foreach( $cat_child as $item ){
									if( $item['image'] == "" ){
										$item['image'] = $image_base = Mage::getModel('catalog/product')->getSmallImageUrl();
									}
								?>
									<div class="item">
										<div class="item-wrap">
											<div class="cat-child-image">
												<img <?php echo $style_img; ?> src="<?php echo $item['image'];?>" alt="<?php echo $item['name'];?>"/>
											</div>
											<div class="cat-child-title">
												<a href="<?php echo $item['link'];?>" <?php echo $helper::parseTarget($this->_getConfig('product_links_target', '_self')) ?>>
													<?php echo $helper->truncate($item['name'], $this->_getConfig('cat_title_maxlength', 25)); ?>
												</a>								
											</div>							
										</div>
									</div>
								<?php }?>
								</div>
							</div>
						</div>
					</div>		
				</div>
				<?php }?>
				<?php
				$pretext = $this->_getConfig('pretext');
				if (!empty($pretext)) {
					?>
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($pretext)->toHtml(); ?>
				<?php } ?>					
			<?php }?>
		</div>
		
		
		<div class="ltabs-wrap ">
			<div class="ltabs-tabs-container" data-delay="<?php echo $this->_getConfig('product_delay', 300); ?>"
			     data-duration="<?php echo $this->_getConfig('product_duration', 600); ?>"
			     data-effect="<?php echo $this->_getConfig('effect'); ?>"
			     data-ajaxurl="<?php echo Mage::getBaseUrl().'supercategories/index/ajax'; ?>" data-modid="<?php echo $tag_id; ?>">
				<!--Begin Tabs-->
				<?php include('default_tabs.phtml'); ?>
				<?php include('default_js.phtml'); ?>
			</div>
			<!-- End Tabs-->
			<div class="ltabs-items-container <?php echo $class_show; ?>"><!--Begin Items-->
				<?php foreach ($list as $items) {
					$child_items = isset($items->child) ? $items->child : '';
					$cls_device = $class_ltabs;
					$cls_animate = $this->_getConfig('effect');
					$cls = (isset($items->sel) && $items->sel == "sel") ? ' ltabs-items-selected ltabs-items-loaded' : '';
					$cls .= ($items->id == "*") ? ' items-category-all' : ' items-category-' . $items->id;
					?>
					<div class="ltabs-items <?php echo $cls; ?>">
						<div class="products-grid ltabs-items-inner <?php echo $cls_device . ' ';
						echo $cls_animate; ?>">
							<?php if (!empty($child_items)) {
								include('default_items.php');
							} else {
								?>
								<div class="ltabs-loading"></div>
							<?php } ?>
						</div>
						<?php if($show_loadmore_slider == 'loadmore') { ?>
							<?php $classloaded = ($this->_getConfig('product_limitation', 5) >= $items->count || $this->_getConfig('product_limitation', 5) == 0) ? 'loaded' : ''; ?>
											<div class="ltabs-loadmore"
												 data-active-content=".items-category-<?php echo ($items->id == "*") ? 'all' : $items->id; ?>"
												 data-categoryid="<?php echo $items->id; ?>"
												 data-rl_start="<?php echo $this->_getConfig('product_limitation', 2) ?>"
												 data-rl_total="<?php echo $items->count ?>"
												 data-rl_allready="
							<?php echo $this->__('All ready'); ?>"
												 data-ajaxurl="
							<?php  echo Mage::getBaseUrl().'supercategories/index/ajax'; ?>" data-modid="
							<?php echo $items->id; ?>"
												 data-rl_load="
							<?php echo $this->_getConfig('source_limit', 2) ?>">
												<div class="ltabs-loadmore-btn <?php echo $classloaded ?>"
													 data-label="
							<?php echo ($classloaded) ? $this->__('All ready') : $this->__('Load more'); ?>">
													<span class="ltabs-image-loading"></span>
													<img class="add-loadmore" src="<?php echo $this->getSkinUrl('sm/supercategories/images/add.png');?>" alt="" />
												</div>
											</div>
						<?php } ?>
					</div>
				<?php } ?>
			</div>
			<!--End Items-->
		</div>

	</div>
	</div>
<?php
} else {
	echo 'Has no item to show!';
} ?>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($){
		/*
        $('#<?php echo $uniqued;?> .slider').responsiver({
			interval: <?php echo $interval; ?>,
			speed: <?php echo $speed; ?>,
			start: <?php echo $start; ?>,
			step: <?php echo $step; ?>,
			circular: true,
			preload: true,
			fx: 'slide',
			pause: '<?php echo $stop;?>',
			control:{
				prev: '#<?php echo $tag_id;?> .control-button li[class="preview"]',
				next: '#<?php echo $tag_id;?> .control-button li[class="next"]'
			},			
			getColumns: function(element){
				var match = $(element).attr('class').match(/cols-(\d+)/);
				if (match[1]){
					var column = parseInt(match[1]);
				} else {
					var column = 1;
				}
				if (!column) column = 1;
				return column;
			}          
        });
		*/
    });
//]]>
</script>

